version: "3.3"

services:
  database:
    container_name:  newsblog_database
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=acosta
      - POSTGRES_USER=acosta
    ports:
      - 5434:5432
